[package]
name = "fm27-dashboard"
version = "11.3.1"
description = "FM27 Manager Dashboard – Begleit-Tool zu Football Manager"
edition = "2021"
publish = false

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
